### ISSUE TITLE
Compatibility with Pimcore Light Theme

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [BlackbitDigitalCommerce/pimcore-data-director#140]
Hi, 

when using data director with the [Pimcore Light Theme ](https://pimcore.com/docs/platform/Light_Theme_Admin_UI/) some UI elements does not fit into the new style or even break the ui. 

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/125017857/14689e3a-d6d1-4006-b060-8463f546e919)
Problem: icons does not match the style of other main menu entries and should not be inverted
Suggestion: use monochrome icons shipped with pimcore. Since pimcore use an invert filter for the light theme, they will work with both, light- and dark theme (https://github.com/pimcore/admin-ui-classic-bundle/tree/1.x/public/img/flat-white-icons)

---

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/125017857/d8070e46-5b04-4bea-8879-5417caaca7be)
Problem: text on selected fields are not readable, because data director style is overwriting pimcores default style for select fields 
in `/Resources/public/css/pim.css`
```css
.x-boundlist-item-over, .x-boundlist-selected {
	background-color: #3c3f41 !important;
}
```
Suggestion: check if this css property is still needed and remove it

Thanks in advance. :)

**Comment by BlackbitDevs** [comment]
> Problem: icons does not match the style of other main menu entries and should not be inverted

Actually the icon never matched the monochrome style. Have now changed it in 3.7 to be monochrome initially but add color on mouseover.

> Problem: text on selected fields are not readable,

Have removed CSS rule
```css
.x-boundlist-item-over, .x-boundlist-selected {
	background-color: #3c3f41 !important;
}
```
