### ISSUE TITLE
Import to HTML WYSIWYG field remove html

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#208]
When I import some data to WYSIWYG field the result is not the same like source.
Looks like some HTML is removed.
I want to import data AS IS.

How to fix it ?

**Comment by betterapp** [comment]
I tried add in both places>

In config.yaml:

```
pimcore:
    object:
        tags:
            wysiwyg:
                defaultEditorConfig:
                    extended_valid_elements: "iframe[src|width|height|name|align],script[type|src],style[type]"
                    valid_elements: "*[*]" 
                    forced_root_block: "" 
                    valid_children: "+body[style],+div[iframe|script]"
```
but when I clear cache I got error

![Image](https://github.com/user-attachments/assets/f8d0d370-1608-4e9a-b01b-7cf8f2b119eb)

I tried add config to field:

```
{
    "extended_valid_elements": "iframe[src|width|height|name|align],script[type|src],style[type]",
    "valid_elements": "*[*]",
    "forced_root_block": "",
    "valid_children": "+body[style],+div[iframe|script]"
}
```

![Image](https://github.com/user-attachments/assets/cf915a06-af06-4b4a-80b0-4f60450a77d4)

Nothing works

**Comment by betterapp** [comment]
https://docs.pimcore.com/platform/Pimcore/Documents/Editables/WYSIWYG/#extending-symfony-html-sanitizer-configuration

**Comment by BlackbitDevs** [comment]
Ok, obviously you found out yourself that the problem was Pimcore's [HTML Sanitizers](https://github.com/pimcore/pimcore/blob/16b3282c175a057be1d81e540701627b2133c15e/bundles/CoreBundle/config/pimcore/default.yaml#L62)
What HTML exactly did not work? Actually my goal is always to make it simply work, and when importing something the goal is to import the exact HTML. So maybe we can bypass the validators... but for this it would be good to know what you wanted to import.

About your try to set the config.yml in https://github.com/BlackbitDigitalCommerce/pimcore-data-director/issues/208#issuecomment-2656285592:
It is object**s*:
```yaml
pimcore:
    objects:
        tags:
```
