### ISSUE TITLE
Call to a member function getLanguage() on nul

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#4]
Hello

I try to setup pipe line import.
I set up everything like in Your video and when I try to run import I get error:

[2022-01-13 11:20:39] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getLanguage() on null" at /.../www/vendor/blackbit/data-director/Controller/RestController.php line 363 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getLanguage() on null at /.../www/vendor/blackbit/data-director/Controller/RestController.php:363)"} []

I use: BDD 2.7.0

**Comment by BlackbitNeueMedien** [comment]
I have just fixed it and released 2.7.8.
But are you sure that the firewall is into place? Because I wonder how you can access the REST API endpoint without a user. Please check your `<Pimcore-Root>/config/packages/security.yaml` for the point firewalls. It should look like this:
```yaml
security:
    ...
    firewalls:
        data_director_webservice_short_urls: '%data_director.security.firewalls.webservice_short_urls%'
        data_director_webservice: '%data_director.security.firewalls.webservice%'
        data_director_webservice_documentation: '%data_director.security.firewalls.webservice_documentation%'
        ...
```
